import turtle
import random
 
screen = turtle.Screen()
turtle.speed(0.5)
screen.setup(width=1400, height=1.0)
screen.bgcolor((0/255, 0/255, 27/255))
# screen.bgcolor("white")
screen.title("Turtle Window")
turtle.penup()
turtle.goto(-1200, -215)
turtle.pendown()
turtle.fillcolor((255/255, 244/255, 243/255))
turtle.begin_fill()
turtle.forward(2800)
turtle.right(90)
turtle.forward(500)
turtle.right(90)
turtle.forward(2800)
turtle.right(90)
turtle.forward(500)
turtle.right(90)
turtle.end_fill()

turtle.penup()
turtle.goto(-450, 0)
turtle.pendown()
turtle.fillcolor("brown")
turtle.begin_fill()
turtle.left(50)
turtle.forward(50)
turtle.right(50)
turtle.forward(20)
turtle.left(90)
turtle.forward(35)
turtle.left(30)
turtle.forward(20)
turtle.right(120)
turtle.forward(5)
turtle.right(60)
turtle.forward(20)
turtle.left(120)
turtle.forward(20)
turtle.right(60)
turtle.forward(5)
turtle.right(120)
turtle.forward(20)
turtle.left(30)
turtle.forward(35)
turtle.left(90)
turtle.forward(20)
turtle.right(45)
turtle.forward(100)
turtle.left(45)
turtle.forward(200)
turtle.left(45)
turtle.forward(30)
turtle.right(90)
turtle.forward(10)
turtle.right(90)
turtle.forward(30)
turtle.left(75)
turtle.forward(30)
turtle.right(30)
turtle.forward(50)
turtle.right(30)
turtle.forward(30)
turtle.right(60)
turtle.forward(30)
turtle.left(120)
turtle.forward(80)
turtle.right(120)
turtle.forward(20)
turtle.right(60)
turtle.forward(80)
turtle.left(120)
turtle.forward(80)
turtle.right(60)
turtle.forward(20)
turtle.right(120)
turtle.forward(80)
turtle.left(120)
turtle.forward(120)
turtle.left(120)
turtle.forward(80)
turtle.right(120)
turtle.forward(20)
turtle.right(60)
turtle.forward(80)
turtle.left(120)
turtle.forward(80)
turtle.right(60)
turtle.forward(20)
turtle.right(120)
turtle.forward(80)
turtle.left(75)
turtle.forward(75)
turtle.left(45)
turtle.forward(70)
turtle.right(45)
turtle.forward(10)
turtle.left(45)
turtle.forward(20)
turtle.right(90)
turtle.forward(35)
turtle.right(60)
turtle.forward(20)
turtle.left(55)
turtle.forward(37)
turtle.end_fill()

turtle.penup()
turtle.goto(-400, 0)
turtle.pendown()
turtle.fillcolor("black")
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()

turtle.penup()
turtle.goto(-75, -15)
turtle.pendown()
turtle.color("white")
turtle.right(85)
turtle.pensize(5)
turtle.forward(200)
turtle.end_fill()
turtle.color("black")
turtle.pensize(1)

turtle.fillcolor("yellow")
turtle.begin_fill()
turtle.right(90)
turtle.forward(180)
turtle.left(90)
turtle.forward(400)
turtle.left(90)
turtle.forward(330)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(350)
turtle.end_fill()
turtle.right(180)

turtle.penup()
turtle.goto(80, -160)
turtle.pendown()
turtle.color((147/255, 91/255, 0/255))
turtle.pensize(5)
turtle.right(60)
turtle.forward(60)
turtle.left(60)
turtle.forward(430)
turtle.left(60)
turtle.forward(60)
turtle.end_fill()
turtle.right(150)

turtle.penup()
turtle.goto(220, -197)
turtle.pendown()
turtle.forward(10)

turtle.penup()
turtle.goto(430, -197)
turtle.pendown()
turtle.forward(10)
turtle.color("black")
turtle.pensize(1)
turtle.left(90)

turtle.penup()
turtle.goto(270, 200)
turtle.pendown()
turtle.fillcolor("beige")
turtle.begin_fill()
turtle.circle(70)
turtle.end_fill()

#draw triangle
turtle.penup()
turtle.goto(204, 290)
turtle.pendown()
turtle.fillcolor("red")
turtle.begin_fill()
turtle.forward(136) 
turtle.left(120)
turtle.forward(140)
turtle.left(120)
turtle.forward(140)
turtle.end_fill()

turtle.fillcolor("black")
turtle.left(120)
turtle.penup()
turtle.goto(200, 290)
turtle.pendown()
turtle.fillcolor("white")
turtle.begin_fill()
turtle.forward(140)
turtle.left(90)
turtle.forward(30)
turtle.left(90)
turtle.forward(140)
turtle.left(90)
turtle.forward(30)
turtle.end_fill()
turtle.right(30)

turtle.fillcolor("black")
turtle.begin_fill()
turtle.penup()
turtle.goto(230, 270)
turtle.pendown()
turtle.circle(10)
turtle.end_fill()

turtle.fillcolor("black")
turtle.begin_fill()
turtle.penup()
turtle.goto(290, 270)
turtle.pendown()
turtle.circle(10)
turtle.left(30)
turtle.end_fill()

turtle.penup()
turtle.goto(270, 260)
turtle.pendown()
turtle.fillcolor("beige")
turtle.begin_fill()
turtle.right(30)
turtle.forward(30)
turtle.left(120)
turtle.forward(30)
turtle.left(120)
turtle.forward(30)
turtle.right(120)
turtle.end_fill()

turtle.penup()
turtle.goto(260, 225)
turtle.pendown()
turtle.fillcolor("red")
turtle.begin_fill()
turtle.right(90)
turtle.circle(10,180)
turtle.end_fill()

turtle.penup()
turtle.goto(230, 212)
turtle.pendown()
turtle.fillcolor("red")
turtle.begin_fill()
turtle.left(90)
turtle.forward(100)
turtle.circle(20)
turtle.left(180)
turtle.penup()
turtle.goto(130,172)
turtle.pendown()
turtle.forward(60)
turtle.right(90)
turtle.forward(80)
turtle.right(30)
turtle.forward(90)
turtle.left(120)
turtle.forward(60)
turtle.right(90)
turtle.forward(25)
turtle.right(90)
turtle.forward(70)
turtle.right(90)
turtle.forward(25)
turtle.right(90)
turtle.forward(70)
turtle.left(45)
turtle.forward(90)
turtle.right(90)
turtle.forward(90)
turtle.left(45)
turtle.forward(70)
turtle.right(90)
turtle.forward(25)
turtle.right(90)
turtle.forward(70)
turtle.right(90)
turtle.forward(25)
turtle.right(90)
turtle.forward(60)
turtle.left(120)
turtle.forward(90)
turtle.right(30)
turtle.forward(80)
turtle.right(90)
turtle.forward(60)
turtle.circle(20)
turtle.left(180)
turtle.penup()
turtle.goto(405,212)
turtle.pendown()
turtle.forward(95)
turtle.end_fill()

turtle.left(90)
turtle.penup()
turtle.goto(260, 200)
turtle.pendown()
turtle.fillcolor("green")
turtle.begin_fill()
turtle.forward(90)
turtle.left(90)
turtle.forward(20)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(20)
turtle.left(90)
turtle.forward(10)
turtle.end_fill()

turtle.left(90)
turtle.penup()
turtle.goto(190, 110)
turtle.pendown()
turtle.fillcolor("green")
turtle.begin_fill()
turtle.forward(156)
turtle.right(90)
turtle.forward(19)
turtle.right(90)
turtle.forward(156)
turtle.right(90)
turtle.forward(19)
turtle.end_fill()

turtle.right(90)
turtle.penup()
turtle.goto(-230, -340)
turtle.pendown()
turtle.hideturtle()
turtle.color("green")
turtle.write("MERRY CHRISTMAS !!!", font=("Verdana",35,"normal"))
turtle.color("black")

colors = ["cyan", "yellow", "light yellow"]
def length_select():
  return random.randint(3,8)

def starts(x,y):
  turtle.hideturtle()
  col = random.choice(colors)
  l = length_select()
  turtle.color(col)
  turtle.penup()
  turtle.goto(x,y)
  turtle.pendown()
  turtle.begin_fill()
  for i in range(5):
    turtle.forward(5)
    turtle.right(144)
    turtle.forward(5)
  turtle.end_fill()  

turtle.pensize(2)

turtle.onscreenclick(starts, 1)
# turtle.hideturtle()

turtle.done()